### PR TITLE
Size of image and video attachments can be set in .env.production

### PR DESCRIPTION
**Pull request by matrix07012**
I made it so you can set the maximal attachment size in `.env.production` in megabytes with `MAX_IMG_SIZE` and `MAX_VID_SIZE`

### CODE REVIEW

**Review by gled-rs — COMMENTED** [review]
Should not it be rather 
(ENV['MAX_IMG_SIZE'] || 8).to_i.megabytes ?
(ENV['MAX_VID_SIZE'] || 40).to_i.megabytes ?

Not sure it is not going to throw an error if the vars are not defined ?

**Comment by matrix07012** [comment]
Tbh honest I haven't tested that. Now that I think about it, it's most likely going to throw an error or set the limit to 0 because .to_i returns zero if the string contains no numbers. I think you are right.

**Comment by gled-rs** [comment]
Please test it and also rebase to current master, there is a small merge conflict.

**Comment by matrix07012** [comment]
I tested it and fixed it.
It didn't show any errors, but a29c06a would set the limit to 0 if the variables weren't present.

**Pull request merged**
